apiVersion: apps/v1
kind: Deployment
metadata:
  name: theremins-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: theremins-nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theremins-http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: theremins-http
  template:
    metadata:
      labels:
        app: theremins-http
    spec:
      containers:
        - name: theremins-http
          image: runarberg/theremins-http:0.2.0
          ports:
            - containerPort: 80
          env:
            - name: THEREMINS_HTTP_PORT
              value: "80"
            - name: THEREMINS_WS_URL
              value: "ws://ws.theremins.club"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theremins-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theremins-ws
  template:
    metadata:
      labels:
        app: theremins-ws
    spec:
      containers:
        - name: theremins-ws
          image: runarberg/theremins-ws:0.2.0
          ports:
            - containerPort: 80
          env:
            - name: THEREMINS_WS_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: theremins-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: theremins-http
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: theremins-http
---
apiVersion: v1
kind: Service
metadata:
  name: theremins-ws
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: theremins-ws
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: theremins-ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
    - host: theremins.club
      http:
        paths:
          - backend:
              serviceName: theremins-http
              servicePort: 80
    - host: ws.theremins.club
      http:
        paths:
          - backend:
              serviceName: theremins-ws
              servicePort: 80
