[package]
name = "theremins-http-server"
version = "0.2.0"
authors = ["runarberg <runarberg@zoho.com>"]

[dependencies]
docopt = "1"
futures = "0.1"
http = "0.1.5"
hyper = "0.12"
serde = "1.0"
serde_derive = "1.0"
